apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-secret-access
  namespace: tailscale
rules:
# Allow get/update/patch only on the specific "tailscale" secret
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["tailscale"]
  verbs: ["get", "update", "patch"]
# Allow creating any secret in the namespace (needed for initial setup)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
# Optional: Allow managing Events for better debugging (as suggested in logs)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "get"]