apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-secret-access-binding
  namespace: tailscale
subjects:
- kind: ServiceAccount
  name: default # IMPORTANT: Change this if your Pod uses a different ServiceAccount
  namespace: tailscale
roleRef:
  kind: Role
  name: tailscale-secret-access # Name of the Role created above
  apiGroup: rbac.authorization.k8s.io